# Generated by Django 4.1 on 2022-08-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('indicatif', models.CharField(blank=True, max_length=200, null=True)),
                ('monnaie', models.CharField(blank=True, max_length=200, null=True)),
                ('cities', models.ManyToManyField(blank=True, to='location.cities')),
            ],
        ),
    ]
